name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 1.0.4
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper
publish_to: none

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  blurrycontainer:
  jidoujisho:
    path: ../
  mecab_dart:
    git:
      url: https://github.com/lrorpilla/mecab_dart
      ref: a822b1ac54ce1fbde33ca7d445c1bfd7dd51ae7c
  bloc: ^6.1.0
  equatable:
  flutter_bloc: ^6.1.1
  flutter_vlc_player: ^5.0.5
  http:
  http_parser:
  ve_dart:
    git:
      url: https://github.com/lrorpilla/ve_dart
      ref: 3ff2d0dcd5dc0fe7e4983f85f9c540d22af1715d
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.2
  pedantic: ^1.10.0-nullsafety.2
  video_player: ^2.0.0-nullsafety.2
flutter:
