name: jidoujisho
description: jidoujisho is an Android video player, reader assistant, OCR image viewer and card creation toolkit with features specifically helpful for language learners. 
publish_to: none

version: 0.26.2+78

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers:
  audio_service: 
    git:
      url: https://github.com/lrorpilla/audio_service
      ref: 1820d8cd19d8248fbfc48ff01a5bee939ea0b858
  auto_orientation:
  async:
  blurrycontainer:
  build_runner:
  chewie:
    path: ./chewie
  clipboard_monitor: ^0.9.1
  crop_image:
  device_info_plus:
  ext_storage:
  external_app_launcher:
  #file_picker: 1.13.3
  gx_file_picker:
  flutter_archive: 3.0.0
  flutter_absolute_path:
  flutter_cache_manager:
  flutter_ffmpeg:
  flutter_inappwebview:
    path: ./flutter_inappwebview
  flutter_vlc_player: ^5.0.5
  flutter_youtube_dl:
    git:
      url: https://github.com/project-violet/flutter-youtube-dl
      ref: 046b5e6c051b3fda333c1f366e2640cd04f763b8
  fluttertoast:
  fuzzy:
  image:
  image_picker:
  intl:
  kana_kit:
  keyboard_visibility: ^0.5.2
  http:
  lazy_load_scrollview: ^1.3.0
  mecab_dart:
    git:
      url: https://github.com/lrorpilla/mecab_dart
      ref: a822b1ac54ce1fbde33ca7d445c1bfd7dd51ae7c
  minimize_app:
  objectbox:
  objectbox_flutter_libs: any
  package_info: ^2.0.2
  path_provider:
  permission_handler:
  photo_view:
      git:
        url: https://github.com/lrorpilla/photo_view
        ref: ae70414abe711b115657fd640527a2a148871847
  progress_indicators:
  receive_sharing_intent:
  share:
  scrollable_positioned_list: ^0.1.9
  screenshot:
  shake_event:
  shell:
  shared_preferences:
  subtitle_wrapper_package:
    path: ./subtitle_wrapper_package
  flutter_tesseract_ocr:
  transparent_image: ^2.0.0
  unofficial_jisho_api:
    git:
      url: https://github.com/lrorpilla/unofficial_jisho_api_dart
      ref: 80eb2c7872fc4d5a8c4df141cace39f782987ae8
  url_launcher:
  ve_dart:
    git:
      url: https://github.com/lrorpilla/ve_dart
      ref: 3ff2d0dcd5dc0fe7e4983f85f9c540d22af1715d
  xml2json:
  youtube_explode_dart:
    git:
      url: https://github.com/Hexer10/youtube_explode_dart
      ref: a51e38dcf8299f11271511922dc90ac48e7f5a47
  youtube_player_flutter:
  wakelock:
dependency_overrides:
  html: ^0.15.0
  http: ^0.13.0
  http_parser: ^4.0.0
  equatable: ^2.0.0
  process: ^3.0.0
  platform: ^3.0.0
  file: ^6.0.0

dev_dependencies:
  flutter_launcher_icons:
  objectbox_generator: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/ipadic/
    - assets/kanjium/accents.txt