name: jidoujisho
description: A mobile video player tailored for Japanese language learners. 
publish_to: none

version: 0.17.1+32

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers:
  audio_service: ^0.17.0
  auto_orientation:
  async:
  chewie:
    path: ./chewie
  clipboard_monitor: ^0.9.1
  device_info:
  ext_storage:
  external_app_launcher:
  gx_file_picker:
  flutter_ffmpeg:
  flutter_vlc_player: ^5.0.5
  flutter_youtube_dl:
    git:
      url: https://github.com/project-violet/flutter-youtube-dl
      ref: 046b5e6c051b3fda333c1f366e2640cd04f763b8
  fuzzy:
  image_picker:
  intl:
  http:
  lazy_load_scrollview: ^1.3.0
  mecab_dart:
    git:
      url: https://github.com/lrorpilla/mecab_dart
      ref: a822b1ac54ce1fbde33ca7d445c1bfd7dd51ae7c
  package_info: ^0.4.3+4
  path_provider:
  permission_handler:
  photo_view:
  progress_indicators:
  receive_sharing_intent:
  scrollable_positioned_list: ^0.1.9
  shell:
  shared_preferences:
  subtitle_wrapper_package:
    path: ./subtitle_wrapper_package
  transparent_image: ^1.0.0
  unofficial_jisho_api:
    git:
      url: https://github.com/lrorpilla/unofficial_jisho_api_dart
      ref: 80eb2c7872fc4d5a8c4df141cace39f782987ae8
  url_launcher:
  ve_dart:
    git:
      url: https://github.com/lrorpilla/ve_dart
      ref: 3ff2d0dcd5dc0fe7e4983f85f9c540d22af1715d
  xml2json:
  youtube_explode_dart:
    git:
      url: https://github.com/Hexer10/youtube_explode_dart
      ref: 721ad7e2d535812e0e90fbe4c4b6175717c44bc5
  youtube_player_flutter:
  wakelock:
dependency_overrides:
  html: ^0.15.0
  http: ^0.13.0
  http_parser: ^4.0.0
  equatable: ^2.0.0
  xml: ^4.2.0
  process: ^4.0.0
  platform: ^3.0.0
  file: ^6.0.0

dev_dependencies:
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/ipadic/
    - assets/kanjium/accents.txt