name: yuuna
description: A full-featured immersion language learning suite for mobile.
publish_to: 'none'
version: 2.5.0+52
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audio_service: ^0.18.9
  audio_session: ^0.1.13
  blurrycontainer:
    git:
      url: https://github.com/Krish-Ideausher/blurry_container/
      ref: fb26dd1fa81edeb048b14703f1c1f28e93ee43d0
  cached_network_image: ^3.2.3
  cancelable_compute: ^1.3.0
  carousel_slider: ^4.2.1
  change_notifier_builder: ^1.1.2
  characters: ^1.2.1
  clipboard: ^0.1.3
  copy_with_extension: ^5.0.2
  crop_image: ^1.0.4
  device_info_plus: ^8.1.0
  document_file_save_plus: ^2.0.0
  easy_pip: ^0.1.0
  expandable: ^5.0.1
  external_app_launcher: ^2.0.2
  external_path: ^1.0.1
  file_picker: ^5.2.5
  filesystem_picker:
    git:
      url: https://github.com/lrorpilla/filesystem_picker
      ref: c0f132e44d2b5387b4babf8a09b7caf257259313
      path: package
  firebase_analytics: ^10.1.5
  firebase_core: ^2.7.1
  firebase_crashlytics: ^3.0.16
  firebase_remote_config: ^4.0.0
  float_column: ^1.4.1
  flutter:
    sdk: flutter
  flutter_accessibility_service: ^0.2.2
  flutter_archive: ^5.0.0
  flutter_cache_manager: ^3.3.0
  flutter_charset_detector: ^1.0.2
  flutter_chatgpt_api:
    git:
      url: https://github.com/lrorpilla/flutter_chatgpt_api
      ref: jidoujisho
  flutter_colorpicker: ^1.0.3
  flutter_exit_app: ^1.0.5
  flutter_fadein: ^2.0.0
  flutter_ffmpeg: ^0.4.2
  flutter_inappwebview:
    git:
      url: https://github.com/lrorpilla/flutter_inappwebview
      ref: jidoujisho
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.8
  flutter_process_text: ^1.1.2
  flutter_reorderable_list: ^1.3.0
  flutter_riverpod: ^1.0.4
  flutter_staggered_grid_view: ^0.6.2
  flutter_vlc_player: ^7.2.0
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.3
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  html: ^0.15.2
  http: ^0.13.4
  image_picker: ^0.8.7
  infinite_carousel: ^1.0.2
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.18.0
  isar: 3.0.6-dev.0
  isar_flutter_libs: 3.0.6-dev.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  just_audio: ^0.9.31
  kana_kit: ^2.0.0
  keframe: ^3.0.0
  lemmatizerx: ^0.0.3
  local_assets_server: ^2.0.2+12
  marquee: ^2.2.3
  material_floating_search_bar: 
    git:
      url: https://github.com/lrorpilla/material_floating_search_bar
      ref: main
  mongol: ^4.0.0
  multi_value_listenable_builder: ^0.0.2
  network_to_file_image: ^4.0.1
  nowplaying: ^2.0.6
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pretty_json: ^2.0.0
  progress_indicators: ^1.0.0
  quiver: ^3.2.1
  receive_intent: ^0.2.3
  receive_sharing_intent: ^1.4.5
  record_mp3: ^3.0.0
  remove_emoji: ^0.0.7
  reorderables: ^0.6.0
  restart_app: ^1.1.2
  ruby_text:
    git:
      url: https://github.com/lrorpilla/RubyText
      ref: cb723f87c9ac575aa735b40016c0ffb3242d921e
  scrollable_positioned_list: ^0.3.5
  share_plus: ^4.0.10
  simple_pip_mode: ^0.8.0
  slang: ^3.13.0
  slang_flutter: ^3.13.0
  sliver_tools: ^0.2.9
  spaces:
    git:
      url: https://github.com/triskell/spaces
      ref: master
  subtitle:
    git:
      url: https://github.com/lrorpilla/subtitle
      ref: ff4a7900d66338c7322a7335f14714f7cb964b82
  system_info: ^1.0.1
  transparent_image: ^2.0.1
  url_launcher: ^6.0.20
  ve_dart:
    git:
      url: https://github.com/lrorpilla/ve_dart
      ref: c366bb1ae24f6fad4f5c7e3a1efad5f2b8122e58
  wakelock: ^0.6.1+2
  web_socket_channel: ^2.3.0
  youtube_explode_dart: ^1.12.4
dependency_overrides:
  ffi: ^2.0.0
  freezed_annotation: ^2.2.0 # Caused by spaces
  gap: ^2.0.1 # Caused by spaces

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^1.0.0
  isar_generator: 3.0.6-dev.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/meta/icon.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/meta/icon-android12.png"

flutter:
  uses-material-design: true

  assets:
    - assets/meta/
    - assets/language/japanese/ipadic/
    - assets/ttu-ebook-reader/
    - assets/ttu-ebook-reader/_app/
    - assets/ttu-ebook-reader/_app/immutable/
    - assets/ttu-ebook-reader/_app/immutable/assets/
    - assets/ttu-ebook-reader/_app/immutable/chunks/
    - assets/ttu-ebook-reader/_app/immutable/entry/
    - assets/ttu-ebook-reader/auth/
    - assets/ttu-ebook-reader/b/
    - assets/ttu-ebook-reader/fonts/
    - assets/ttu-ebook-reader/icons/
    - assets/ttu-ebook-reader/manage/
    - assets/ttu-ebook-reader/settings/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700