name: yuuna
description: A full-featured immersion language learning suite for mobile.
publish_to: 'none'
version: 2.8.8+103
environment:
  sdk: ">=3.0.0<4.0.0"
  flutter: "^3.10.6"

dependencies:
  audio_service: ^0.18.9
  audio_session: ^0.1.13
  blurrycontainer:
    git:
      url: https://github.com/lrorpilla/blurry_container/
      ref: fb26dd1fa81edeb048b14703f1c1f28e93ee43d0
  cached_network_image: ^3.2.3
  cached_network_svg_image: ^0.0.5
  cancelable_compute: ^1.3.0
  carousel_slider: ^4.2.1
  change_notifier_builder: ^1.1.2
  chat_gpt_sdk: ^2.1.5
  clipboard: ^0.1.3
  collection: ^1.17.0
  copy_with_extension: ^5.0.2
  crop_image: ^1.0.4
  device_info_plus: ^8.1.0
  dio: ^5.1.1
  document_file_save_plus: ^2.0.0
  expandable: ^5.0.1
  external_app_launcher: ^3.1.0
  external_path: ^1.0.1
  favicon: ^1.1.1
  file_picker: ^5.3.0
  filesystem_picker:
    git:
      url: https://github.com/lrorpilla/filesystem_picker
      ref: jidoujisho
      path: package
  float_column: ^2.0.0
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_cache_manager: ^3.3.0
  flutter_charset_detector: ^1.0.2
  flutter_colorpicker: ^1.0.3
  flutter_exit_app: ^1.0.5
  flutter_ffmpeg: ^0.4.2
  flutter_gpt_tokenizer: ^0.1.0
  flutter_image_compress: ^1.1.3
  flutter_inappwebview:
    git:
      url: https://github.com/lrorpilla/flutter_inappwebview
      ref: 759bd376214a763ab17ce2ede2c5a00b38330e13
  flutter_launcher_icons: ^0.12.0
  flutter_logs: ^2.1.10
  flutter_native_splash: ^2.2.8
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_vlc_player:
   git:
      url: https://github.com/lrorpilla/flutter_vlc_player
      ref: 013632b4cc591c68ced04ccc0244c2770daca633
      path: flutter_vlc_player
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.4
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  html: ^0.15.2
  http: ^0.13.4
  image_picker: ^0.8.7
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1
  just_audio: ^0.9.31
  kana_kit: ^2.0.0
  lemmatizerx: ^1.0.0
  local_assets_server: ^2.0.2+12
  marquee: ^2.2.3
  material_floating_search_bar: 
    git:
      url: https://github.com/lrorpilla/material_floating_search_bar
      ref: jidoujisho
  mecab_dart: ^0.1.3
  multi_value_listenable_builder: ^0.0.2
  network_to_file_image: ^4.0.1
  nowplaying:
    git: 
      url: https://github.com/lrorpilla/nowplaying
      ref: 290ee1097d67cafc50f3aba1ba5bba01e758d877
  package_info_plus: ^4.0.2
  path: ^1.8.2
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  progress_indicators: ^1.0.0
  quiver: ^3.2.1
  receive_intent:
    git:
      url: https://github.com/lrorpilla/receive_intent
      ref: 3854d07f8f4e9d5a78589639b18b5d454ddf54a0
  record_mp3: ^3.0.0
  remove_emoji: ^0.0.7
  reorderables: ^0.6.0
  restart_app: ^1.1.2
  ruby_text:
    git:
      url: https://github.com/lrorpilla/RubyText
      ref: cb723f87c9ac575aa735b40016c0ffb3242d921e
  scrollable_positioned_list: ^0.3.5
  share_plus: ^4.0.10
  slang: ^3.13.0
  slang_flutter: ^3.13.0
  sliver_tools: ^0.2.9
  spaces:
    git:
      url: https://github.com/lrorpilla/spaces
      ref: master
  subtitle:
    git:
      url: https://github.com/lrorpilla/subtitle
      ref: 36562dcda59c67c170f6e0a10ad5f775eb3341e3
  transparent_image: ^2.0.1
  uri_to_file: ^0.2.0
  url_launcher: ^6.0.20
  ve_dart:
    git:
      url: https://github.com/lrorpilla/ve_dart
      ref: c366bb1ae24f6fad4f5c7e3a1efad5f2b8122e58
  visibility_detector: ^0.4.0+2
  wakelock:
    git:
      url: https://github.com/diegotori/wakelock
      ref: 40464c75e908f57f458597ef4912f5273ab89b1a
      path: wakelock
  web_socket_channel: ^2.3.0
  youtube_explode_dart: ^1.12.4
  
dependency_overrides:
  ffi: ^2.0.0
  freezed_annotation: ^2.2.0 # Caused by spaces
  gap: ^3.0.0 # Caused by spaces
  wakelock_windows:
    git:
      url: https://github.com/diegotori/wakelock
      ref: 40464c75e908f57f458597ef4912f5273ab89b1a
      path: wakelock_windows

dev_dependencies:
  build_runner: ^2.3.3
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.1
  isar_generator: ^3.1.0+1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/meta/icon.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/meta/icon-android12.png"

flutter:
  uses-material-design: true

  assets:
    - assets/licenses/
    - assets/meta/
    - assets/language/japanese/ipadic/
    - assets/ttu-ebook-reader/
    - assets/ttu-ebook-reader/_app/
    - assets/ttu-ebook-reader/_app/immutable/
    - assets/ttu-ebook-reader/_app/immutable/assets/
    - assets/ttu-ebook-reader/_app/immutable/chunks/
    - assets/ttu-ebook-reader/_app/immutable/components/
    - assets/ttu-ebook-reader/_app/immutable/components/pages/
    - assets/ttu-ebook-reader/_app/immutable/components/pages/auth/
    - assets/ttu-ebook-reader/_app/immutable/components/pages/b/
    - assets/ttu-ebook-reader/_app/immutable/components/pages/manage/
    - assets/ttu-ebook-reader/_app/immutable/components/pages/settings/
    - assets/ttu-ebook-reader/auth/
    - assets/ttu-ebook-reader/b/
    - assets/ttu-ebook-reader/fonts/
    - assets/ttu-ebook-reader/icons/
    - assets/ttu-ebook-reader/manage/
    - assets/ttu-ebook-reader/settings/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700