name: flutter_vlc_player
description: A VLC-powered alternative to Flutter's video_player. Supports multiple players on one screen.
version: 5.0.3
homepage: https://github.com/solid-software/flutter_vlc_player/

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: software.solid.fluttervlcplayer
        pluginClass: FlutterVlcPlayerPlugin
      ios:
        pluginClass: FlutterVlcPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  cryptoutils: ^0.4.0
  meta: ^1.2.4
  flutter_vlc_player_platform_interface: ^1.0.2
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^0.1.17
  plugin_platform_interface: ^1.0.3

