name: Build Android APK
on:
  push:
    branches: ['main']
    paths: ['yuuna/**']
  pull_request:
    branches: ['main']
    paths: ['yuuna/**']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6'
    - run: flutter pub get
      working-directory: yuuna
    - run: flutter pub run build_runner build --delete-conflicting-outputs
      working-directory: yuuna
    - run: flutter analyze
      working-directory: yuuna
    - run: flutter build apk --target-platform=android-arm64
      working-directory: yuuna
